### ISSUE TITLE
User should be able to resume simulation from a checkpoint from the cache

### ISSUE THREAD

**Issue by rht** [Logende/mesa-replay#1]
Imagine a simulation that would take a very long time: we should be able to run 50% of it, save to cache, then resume from the cache at the 50% checkpoint to complete the simulation. This is analogous to checkpoints when we train ML models.

**Comment by Logende** [comment]
Should now be possible, thanks to the run_model_until_condition_met function (see [this](https://github.com/Logende/mesa-replay/commit/ff94c068ff3042f0aebbf0b4580f2ed93ea28972) commit).

Example usage:
```
model = MyModel()
model = CacheableModel(model, "my_cache.cache", cache_state=CacheState.RECORD)

# simulate and record until checkpoint reached
model. run_model_until_condition_met(<custom checkpoint condition>)

# tell CacheableModel to finish the run by persisting it to the cache file on the file system
model.finish_run()
```

Then to resume:

```
actual_model = MyModel()
model = CacheableModel(actual_model, "my_cache.cache", cache_state=CacheState.REPLAY)

# replay until same checkpoint reached. The underlying actual_model will now be in the same state as when reaching the checkpoint originally
model.run_model_until_condition_met(<custom checkpoint condition>)

# Option A: continue simulation regularly, without recording and without Mesa-Replay:
actual_model.run_model()

# Option B: Continue simulation and record that part as well. It will start a new cache though, as we use a new CacheableModel. See we should use a new cache file for that second part of the run.
model = CacheableModel(actual_model, "my_cache_part2.cache", cache_state=CacheState.RECORD)
model.run_model()
```

**Comment by Logende** [comment]
Note that for "resuming at some point", further optimizations would be possible. Instead of replaying everything from cache, we could simply jump to the lates entry from the cache directly (exception: not possible if we use StreamingCacheableModel, then we always have to go through the complete stream).
